Traceback (most recent call last):
  File "/Users/loreliegordon/.virtualenvs/sandbox2/lib/python3.7/site-packages/nbclient/client.py", line 627, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Users/loreliegordon/.virtualenvs/sandbox2/lib/python3.7/site-packages/nbclient/util.py", line 89, in ensure_async
    result = await obj
  File "/Users/loreliegordon/.virtualenvs/sandbox2/lib/python3.7/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loreliegordon/.virtualenvs/sandbox2/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/loreliegordon/.virtualenvs/sandbox2/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/loreliegordon/.virtualenvs/sandbox2/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/loreliegordon/.virtualenvs/sandbox2/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/loreliegordon/.virtualenvs/sandbox2/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/loreliegordon/.virtualenvs/sandbox2/lib/python3.7/site-packages/nbclient/client.py", line 846, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/loreliegordon/.virtualenvs/sandbox2/lib/python3.7/site-packages/nbclient/client.py", line 651, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/Users/loreliegordon/.virtualenvs/sandbox2/lib/python3.7/site-packages/nbclient/client.py", line 702, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['y_test_1_y_pred_1 = []', 'y_test_0_y_pred_0 = []', 'y_test_1_y_pred_0 = []', 'y_test_0_y_pred_1 = []', '']
...
['all_losses_df = np.array(all_losses)', 'all_losses_df = all_losses_df.reshape(len(all_losses_df), len(all_losses_df[0]))', 'all_losses_df = pd.DataFrame(all_losses_df).T', 'all_losses_df["iter"] = all_losses_df.index', 'all_losses_df = all_losses_df.melt(id_vars=["iter"])']
-------------------

